mutation createPage ($path: String!, $title: String!, $description: String!, $editor: String!, $locale: String!, $content: String!) {
  pages {
    create(
      path: $path,
      title: $title,
      locale: $locale,
      content: $content
      description: $description,
      editor: $editor,
      isPublished: true,
      isPrivate: false,
      tags: [],
    ) {
      responseResult {
      succeeded
      errorCode
      slug
      message
    }
    page {
      id
      path
      title
    }
    }
  }
}
