query getPage($path: String!, $locale: String!) {
  pages {
    singleByPath (path: $path, locale: $locale) {
      id
      path
      title
      description
      content
      createdAt
      updatedAt
    }
  }
}
